### ISSUE TITLE
can't import

### ISSUE THREAD

**Issue by hiqqs** [hugop95/discord-table#1]
trying to import this but getting error:

```Error: Cannot find module '/Users/higgs/github/swgoh-drice/node_modules/@hugop/discord-table/@hugop/discord-table/dist/discord-table.js'. Please verify that the package.json has a valid "main" entry```

**Comment by hiqqs** [comment]
i was able to by referencing the package name like this:
`const dcTable = require('@hugop/discord-table/dist/discord-table.js')`

running into format issues but hoping i can config and use

**Comment by hiqqs** [comment]
this is awesome, thank you

**Comment by hugop95** [comment]
Hello, I'll work on fixing this as soon as I can
